name: Keep Render Awake

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch: # allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping backend
        run: |
          curl -s https://chatting-app-nestjs.onrender.com
          echo "Ping sent at $(date)"
