name: Keep Render Awake

on:
  schedule:
    - cron: "*/14 * * * *" # Every 14 mins is perfect for Render
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend with retry
        run: |
          # --connect-timeout: waits 30s to connect
          # --retry: tries 3 times if it fails
          curl -s --connect-timeout 30 --retry 3 https://chatting-app-nestjs.onrender.com
          echo "Ping successful at $(date)"
